-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 14:46:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partners` (
  `id` INT NOT NULL,
  `partners_name` VARCHAR(45) NOT NULL,
  `partners_loc` VARCHAR(45) NOT NULL,
  `partners_num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idpartners_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resto` (
  `id` INT NOT NULL,
  `resto_name` VARCHAR(45) NOT NULL,
  `resto_found_date` VARCHAR(45) NOT NULL,
  `resto_owner` VARCHAR(45) NOT NULL,
  `partners_idpartners` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idresto_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_resto_partners_idx` (`partners_idpartners` ASC) VISIBLE,
  CONSTRAINT `fk_resto_partners`
    FOREIGN KEY (`partners_idpartners`)
    REFERENCES `mydb`.`partners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL,
  `cust_lname` VARCHAR(45) NOT NULL,
  `cust_fname` VARCHAR(45) NOT NULL,
  `cust_initial` VARCHAR(45) NOT NULL,
  `resto_idresto` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcustomer_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_customer_resto1_idx` (`resto_idresto` ASC) VISIBLE,
  CONSTRAINT `fk_customer_resto1`
    FOREIGN KEY (`resto_idresto`)
    REFERENCES `mydb`.`resto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food` (
  `id` INT NOT NULL,
  `food_name` VARCHAR(45) NOT NULL,
  `food_price` INT NOT NULL,
  `food_type` VARCHAR(45) NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idfood_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_food_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_food_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL,
  `order_date` VARCHAR(45) NOT NULL,
  `order_delivery` VARCHAR(45) NOT NULL,
  `order_status` VARCHAR(45) NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id` INT NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `ch_name` VARCHAR(45) NOT NULL,
  `card_num` VARCHAR(45) NOT NULL,
  `card_sec_code` VARCHAR(45) NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_payment_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL,
  `emp_lname` VARCHAR(45) NOT NULL,
  `emp_initial` VARCHAR(45) NOT NULL,
  `emp_add` VARCHAR(45) NOT NULL,
  `emp_email` VARCHAR(45) NOT NULL,
  `emp_phone` INT(15) NOT NULL,
  `emp_type` VARCHAR(45) NOT NULL,
  `payment_payment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_payment1_idx` (`payment_payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_payment1`
    FOREIGN KEY (`payment_payment_id`)
    REFERENCES `mydb`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
